const CONSTANTS = {
  STYLES: {
    SPACING: 16,
    BORDER_RADIUS: 8,
  },
  SOCKET_EVENTS: {
    CONNECTED: "CONNECTED",
    GET_ACTIVE_USERS: "GET_ACTIVE_USERS",
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    CREATE_NEW_CHAT: "CREATE_NEW_CHAT",
    GET_CHATS: "GET_CHATS"
  }
}

export default CONSTANTS
