const CONSTANTS = {
  STYLES: {
    SPACING: 16,
    BORDER_RADIUS: 8,
  },
  SOCKET_EVENTS: {
    USER_ONLINE: "USER_ONLINE",
    USER_OFFLINE:"USER_OFFLINE",
    GET_ACTIVE_USERS: "GET_ACTIVE_USERS"

  }
}

export default CONSTANTS
