const CONSTANTS = {
  STYLES: {
    SPACING: 16,
    BORDER_RADIUS: 8,
    ICON_SIZE: 16,
  },
  SOCKET_EVENTS: {
    ERROR: "ERROR",
    CONNECTED: "CONNECTED",
    GET_ACTIVE_USERS: "GET_ACTIVE_USERS",
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    CREATE_NEW_CHAT: "CREATE_NEW_CHAT",
    GET_CHATS: "GET_CHATS",
    GET_CURRENT_CHAT_MESSAGES :"GET_CURRENT_CHAT_MESSAGES",
    SEND_MESSAGE: "SEND_MESSAGE",
    LOAD_MORE_MESSAGES: "LOAD_MORE_MESSAGES",
    REACT_MESSAGE: "REACT_MESSAGE",
    REPLY_MESSAGE: "REPLY_MESSAGE"
  }
}

export default CONSTANTS
